## <font color="lime">BA 305 - Team Exercise<font>

---

### Teaching Team Pre-Processing Data Before Distributing the Exercise

##### - We are splitting the original train dataset into two parts

- 80% for students to train and test their models
- 20% for us to evaluate their models
- Create a sample submission file based on the 20% split

---

#### Following is how the codes work

Step 1: Load the Dataset
First, load the dataset from the uploaded train.csv file.

Step 2: Split the Dataset
Split the dataset into an 80% portion for students and a 20% portion for evaluation. We'll use train_test_split from sklearn.model_selection for this purpose.

Step 3: Save the 80% Split
Save the 80% portion as a CSV file for students. This file will be used by students to train and validate their models.

Step 4: Prepare the Evaluation Split
For the 20% evaluation split, prepare two files: one with the features (excluding the labels) for students to make predictions on, and another with the actual labels, which you'll keep private for evaluation.

Step 5: Create a Sample Submission File
Create a sample submission file to guide students on how the submission should be formatted. This file will mimic the structure of the 20% features file but include mock predictions.

---

#### Output Files:
- Student Training Data:
    - student_training_data.csv - This file contains the 80% split of the dataset for students to train and test their models.

- Evaluation Features: 
    - evaluation_features.csv - This file has the features from the 20% split for students to make predictions on.

- Sample Submission:
    - sample_submission.csv - A template showing how students should format their predictions for submission.

---

In [1]:
# TODO
# Change the Following Variables

# Where is the original data?
original_data_path = './original-data/heart_disease.xlsx'

# Where should the 80% student data be saved?
student_data_path = './student-data'

# Where should the evaluation data label be saved?
evaluation_data_path = './evaluation-data'

# What is the variable name for the label?
data_label = 'HeartDisease'

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [3]:
import pandas as pd

# READ EXCEL FILE
df = pd.read_excel(original_data_path, sheet_name='data', index_col=0)

dictionary = pd.read_excel(original_data_path, sheet_name='data_dict')

In [39]:
df

,ID,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,1,No,16.60,Yes,No,No,3,30,No,Female,55-59,White,Yes,Yes,Very good,5,Yes,No,Yes
1,2,No,20.34,No,No,Yes,0,0,No,Female,80 or older,White,No,Yes,Very good,7,No,No,No
2,3,No,26.58,Yes,No,No,20,30,No,Male,65-69,White,Yes,Yes,Fair,8,Yes,No,No
3,4,No,24.21,No,No,No,0,0,No,Female,75-79,White,No,No,Good,6,No,No,Yes
4,5,No,23.71,No,No,No,28,0,Yes,Female,40-44,White,No,Yes,Very good,8,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,319791,Yes,27.41,Yes,No,No,7,0,Yes,Male,60-64,Hispanic,Yes,No,Fair,6,Yes,No,No
319791,319792,No,29.84,Yes,No,No,0,0,No,Male,35-39,Hispanic,No,Yes,Very good,5,Yes,No,No
319792,319793,No,24.24,No,No,No,0,0,No,Female,45-49,Hispanic,No,Yes,Good,6,No,No,No
319793,319794,No,32.81,No,No,No,0,0,No,Female,25-29,Hispanic,No,No,Good,12,No,No,No
319794,319795,No,46.56,No,No,No,0,0,No,Female,80 or older,Hispanic,No,Yes,Good,8,No,No,No

In [40]:
dictionary

             Column1                                            Column2
0        Column Name                                        Description
1       HeartDisease  0="No"; 1="Yes"; Respondents that have ever re...
2                BMI                              Body Mass Index (BMI)
3            Smoking  Have you smoked at least 100 cigarettes in you...
4    AlcoholDrinking  Heavy drinkers (adult men having more than 14 ...
5             Stroke                    (Ever told) (you had) a stroke?
6     PhysicalHealth  Now thinking about your physical health, which...
7       MentalHealth  Thinking about your mental health, for how man...
8        DiffWalking  Do you have serious difficulty walking or clim...
9                Sex                            Are you male or female?
10       AgeCategory                        Fourteen-level age category
11              Race                       Imputed race/ethnicity value
12          Diabetic                    (Ever told) (you had) diabetes?
13  PhysicalActivity  Adults who reported doing physical activity or...
14         GenHealth    Would you say that in general your health is...
15         SleepTime  On average, how many hours of sleep do you get...
16            Asthma                      (Ever told) (you had) asthma?
17     KidneyDisease  Not including kidney stones, bladder infection...
18        SkinCancer                 (Ever told) (you had) skin cancer?

In [41]:
# OPTIONAL
## Change the 'y' or 'HeartDisease' value to binary 0 and 1

df['HeartDisease'] = df['HeartDisease'].map(lambda x : 1 if x=='Yes' else 0)
df.HeartDisease.unique()

array([0, 1])

In [42]:
# Load the dataset
# df = pd.read_csv(original_data_path)

# Reindex the dataset
df.reset_index(inplace=True, drop=True)

# Split the dataset into training (80%) and evaluation (20%) sets, maintaining the index
train_df, eval_df = train_test_split(df, test_size=0.2, random_state=42, stratify=df[data_label])

# Save the 80% split for students without the index
train_df.reset_index(drop=True).to_csv(student_data_path + '/team_exercise_data.csv', index=False)

# Prepare the evaluation split: features for students and labels for evaluation
eval_features = eval_df.drop(columns=[data_label])
eval_labels = eval_df[[data_label]]

# Save the evaluation features for students, including the index
eval_features.to_csv(student_data_path + '/eval.csv', index=True)

# Save the actual labels privately for your evaluation, including the index
eval_labels.to_csv(evaluation_data_path + '/answer.csv', index=True)

# Create a sample submission file, using the index from the evaluation features
sample_submission = eval_features.copy()
sample_submission[data_label] = 0  # Mock predictions, replace 0 with the model's predictions
sample_submission[[data_label]].to_csv(student_data_path + '/sample_submission.csv', index=True)
sample_submission[[data_label]].to_csv(student_data_path + '/sample_submission.csv', index=True)

In [43]:
dictionary.to_csv(student_data_path + '/data_dictionary.csv', index=False)

---

#### Check the data

In [44]:
student_data = pd.read_csv(student_data_path + '/team_exercise_data.csv')
student_data

,ID,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,143356,0,23.62,Yes,No,No,30,30,Yes,Female,45-49,White,No,No,Fair,5,Yes,No,No
1,290536,0,22.43,No,No,No,1,0,No,Male,25-29,White,No,Yes,Very good,8,No,No,No
2,31529,0,33.28,Yes,No,No,20,30,No,Female,30-34,Hispanic,No,No,Fair,7,No,No,No
3,234535,0,24.96,Yes,No,No,0,0,No,Female,65-69,White,No,Yes,Very good,8,No,No,No
4,264814,0,27.25,Yes,No,No,0,0,No,Female,55-59,White,No,Yes,Very good,5,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255831,52260,0,30.81,Yes,No,Yes,0,0,No,Male,65-69,White,No,Yes,Excellent,5,Yes,No,No
255832,237010,0,20.16,Yes,No,No,0,8,Yes,Male,30-34,White,No,Yes,Good,7,No,No,No
255833,89082,0,18.89,No,No,No,0,0,No,Female,35-39,White,No,Yes,Excellent,7,No,No,No
255834,117491,0,25.02,No,No,No,0,0,No,Male,80 or older,White,Yes,Yes,Good,8,No,No,No
255835,241204,0,32.55,No,No,No,0,0,No,Male,55-59,White,No,Yes,Good,7,No,No,No

In [45]:
student_test = pd.read_csv(student_data_path + '/eval.csv')
student_test

,ID,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
229267,229268,27.12,No,No,No,30,7,No,Male,45-49,White,Yes,Yes,Fair,8,No,No,No
133926,133927,49.39,Yes,No,No,25,2,Yes,Female,45-49,White,No,Yes,Fair,6,Yes,No,No
307338,307339,32.92,No,No,No,3,29,No,Female,35-39,White,No,Yes,Good,8,Yes,No,No
284517,284518,26.36,Yes,No,No,0,0,No,Male,70-74,White,No,Yes,Fair,7,No,No,No
58968,58969,22.71,No,No,No,0,10,No,Female,65-69,White,No,Yes,Excellent,7,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233107,233108,29.21,Yes,No,No,2,10,Yes,Male,60-64,White,Yes,Yes,Very good,7,No,No,No
169205,169206,30.41,No,No,No,0,0,No,Male,60-64,White,No,Yes,Excellent,7,No,No,No
47453,47454,38.52,No,No,No,2,0,No,Male,60-64,Black,No,Yes,Fair,22,No,Yes,No
294418,294419,33.00,Yes,No,No,2,0,No,Male,70-74,Other,No,Yes,Good,8,No,Yes,No
181730,181731,26.54,Yes,No,No,0,0,No,Male,75-79,White,No,Yes,Excellent,8,No,No,Yes

In [46]:
sample = pd.read_csv(student_data_path + '/sample_submission.csv', index_col=0)
sample

        HeartDisease
229267             0
133926             0
307338             0
284517             0
58968              0
...              ...
233107             0
169205             0
47453              0
294418             0
181730             0

[63959 rows x 1 columns]

In [47]:
answer = pd.read_csv(evaluation_data_path + '/answer.csv', index_col=0)
answer

        HeartDisease
229267             0
133926             0
307338             0
284517             0
58968              0
...              ...
233107             0
169205             0
47453              0
294418             0
181730             1

[63959 rows x 1 columns]

In [48]:
data_dictionary = pd.read_csv(student_data_path + '/data_dictionary.csv')
data_dictionary

             Column1                                            Column2
0        Column Name                                        Description
1       HeartDisease  0="No"; 1="Yes"; Respondents that have ever re...
2                BMI                              Body Mass Index (BMI)
3            Smoking  Have you smoked at least 100 cigarettes in you...
4    AlcoholDrinking  Heavy drinkers (adult men having more than 14 ...
5             Stroke                    (Ever told) (you had) a stroke?
6     PhysicalHealth  Now thinking about your physical health, which...
7       MentalHealth  Thinking about your mental health, for how man...
8        DiffWalking  Do you have serious difficulty walking or clim...
9                Sex                            Are you male or female?
10       AgeCategory                        Fourteen-level age category
11              Race                       Imputed race/ethnicity value
12          Diabetic                    (Ever told) (you had) diabetes?
13  PhysicalActivity  Adults who reported doing physical activity or...
14         GenHealth    Would you say that in general your health is...
15         SleepTime  On average, how many hours of sleep do you get...
16            Asthma                      (Ever told) (you had) asthma?
17     KidneyDisease  Not including kidney stones, bladder infection...
18        SkinCancer                 (Ever told) (you had) skin cancer?